### ISSUE TITLE
pages: robots.txt: editing faulty

### ISSUE THREAD

**Issue by Thomas-Pelster** [kestrel-1/report-an-issue#8]
- It is possible to click on edit in the pages view at robots.txt, then a new browser window opens but neither the content is displayed nor can you edit anything.
- The same with manifest.json and serviceworker.js

**Comment by reusr1** [comment]
@Thomas-Pelster this issue has been fixed with the latest deployment - would you mind checking if this also works for you and close the issue if it works? thank you

**Comment by Thomas-Pelster** [comment]
@reusr1 The solution is that these files are no longer listed under pages?

- For manifest.json and serviceworker.js is that solution okay
- Editing the robots.txt I found quite nice.

**Comment by Thomas-Pelster** [comment]
- The problem still exists. It is possible to view the robots.txt in a new tab, but editing in a new tab still shows an empty editor.
- Setup: macOS 10.15.6, Chrome 84.0, Site: Thomas2

![20200814_Kestrel1_robots](https://user-images.githubusercontent.com/50134764/90232197-95173c80-de1c-11ea-9bd5-b8742e0d20a7.gif)

**Comment by Thomas-Pelster** [comment]
@reusr1 Fixed!

**Comment by reusr1** [comment]
@Thomas-Pelster thank you! closing the issue
